### ISSUE TITLE
Query local node to convert between `POSIXTime` and `SlotNo`

### ISSUE THREAD

**Issue by Saizan** [mlabs-haskell/bot-plutus-interface#100]
Currently `bot-plutus-interface` uses `plutus-ledger` to convert between `POSIXTime` and `SlotNo`, however that does not necessarily match what the cardano node is doing, because slot length can change along the lifetime of the chain (and has [changed on testnet](https://cardano.stackexchange.com/questions/6955/when-was-the-slot-duration-set-to-1-sec-on-cardano-testnet)).

Inaccurate conversion affects in particular validators that try to match the validity range of a transaction with info stored in the datums.

I documented in this comment https://github.com/Plutonomicon/cardano-transaction-lib/issues/410#issuecomment-1127456187 how `cardano-ledger` translates the `SlotNo` in the validity range during validation.

Ultimately it relies on the `slotToWallclock` query from `ouroboros-network` (which is used to build the `EpochInfo` record).
This latter package also has a `wallclockToSlot` query to convert the other way:
https://github.com/input-output-hk/ouroboros-network/blob/bd9e5653647c3489567e02789b0ec5b75c726db2/ouroboros-consensus/src/Ouroboros/Consensus/HardFork/History/Qry.hs#L461-L481

I believe that BPI should base all time and slot conversion on such queries (or maybe `EpochInfo` for the slot to time direction).
Most operations where we need this already query the node for some info anyway so I think the extra `EraHistory` query necessary should not cause responsiveness problems.

**Comment by mikekeke** [comment]
PR: #105
