### ISSUE TITLE
Should Ada change get its own UTxO?

### ISSUE THREAD

**Issue by samuelWilliams99** [mlabs-haskell/bot-plutus-interface#56]
Currently, in say a transaction where we send a token from one wallet to another, where the sender has a minimum ada UTxO with the special token, and a second UTxO with ada only (which is used for collateral), the change for that transaction (so the special tokens AND the excess Ada) end up in one UTxO.
This means that now we have no ada-only collaterals in the wallet - it essentially bricks itself until it receives Ada externally.
Perhaps all change Ada should always end up in a separate UTxO - if the change is higher than the min UTxO amount.

Curious of peoples thoughts here.

**Comment by samuelWilliams99** [comment]
@gege251

**Comment by gege251** [comment]
That's an interesting problem. I see another solution, similar to what Nami does: making it possible to use a selected utxo as collateral, or even using a separate wallet for collaterals only. I think that would also be better than the current "random" collateral picking, that way we could control how much we want to risk (in case the collateral is lost, the whole utxo will be lost).

**Comment by samuelWilliams99** [comment]
A separate wallet might be a bit too involved (and increase fees), but i like the idea of defining a single UTxO thats always collateral, and not allowing it to be used in inputs.
Obviously, if a tx ever failed, config would need to be changed.
Maybe we optimise collateral selecting to pick the minimum viable UTxO, and never use that as input?

**Comment by gege251** [comment]
Optimising collateral selection would be the most ergonomic way to do this, it sounds good to me.
One drawback I can think of with this is when there's only one utxo at the address. We could engineer something around this problem, splitting the utxo... on the other hand if only bpi is controlling the address, then this could not occur except maybe at the first time one sets up the address, so maybe a good error message and some documentation would be enough.

**Comment by samuelWilliams99** [comment]
Yeah, the single UTxO issue generalises to when theres only a single ada utxo, since we'd need it for fees. If someone did just send a large UTxO of Ada for just covering fees , or even several large Ada UTxOs, we'd be using a hugely overkill collateral. We'd ideally want to put a bounded ada value on eligable collaterals, then document the requirement of one or many UTxOs of this style.
This may also affect parallelisability, since I believe we cannot use the same UTxO as collerateral in multiple transactions in 1 block (though i may be wrong here, but if I am, I'm unsure how Cardano would handle if both txs failed)

**Comment by gege251** [comment]
Maybe we could handle this together with some coin selection optimisations: #32

**Comment by samuelWilliams99** [comment]
Yeah for sure, some further thought on what that coin optimisation would look like is needed. Its almost a bin packing algo but with multiple resources (maybe theres already an algo for that?)
